export enum OrderStatus {
  AGUARDANDO_PAGAMENTO = "AGUARDANDO_PAGAMENTO",
  PAGAMENTO_REJEITADO = "PAGAMENTO_REJEITADO",
  PAGAMENTO_COM_SUCESSO = "PAGAMENTO_COM_SUCESSO",
  AGUARDANDO_RETIRADA = "AGUARDANDO_RETIRADA",
  EM_TRANSITO = "EM_TRANSITO",
  ENTREGUE = "ENTREGUE",
}
